### ISSUE TITLE
Multiple Instances - Feature Request

### ISSUE THREAD

**Issue by dac21** [bieniu/ha-accuweather#1]
I typically track weather data for two locations.  Is it possible to enter a second integration configuration to accomplish this?

**Comment by bieniu** [comment]
No, there are only 50 request for weather data per day allowed. This is barely enough for one instance.

**Comment by dac21** [comment]
So can I create a second API and then add accuweather a second time with the second API? Sent from Mail for Windows 10 From: Maciej BieniekSent: Thursday, June 25, 2020 1:42 AMTo: bieniu/ha-accuweatherCc: dac21; AuthorSubject: Re: [bieniu/ha-accuweather] Multiple Instances - Feature Request (#1) No, there are only 50 request for weather data per day allowed. This is barely enough for one instance.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bieniu** [comment]
This doesn't comply with the terms of use of the API. One free API key per person. This component will go to the official HA repository in the future so it must comply with the AccuWeather API terms of use.
