### ISSUE TITLE
Percipitation value not rounded

### ISSUE THREAD

**Issue by maxwroc** [bieniu/ha-accuweather#2]
![image](https://user-images.githubusercontent.com/8268674/85960087-aef9de80-b998-11ea-8721-709c4cd6a129.png)

![image](https://user-images.githubusercontent.com/8268674/85960096-c769f900-b998-11ea-9f22-41178e6764a4.png)

**Comment by bieniu** [comment]
Fixed via https://github.com/bieniu/ha-accuweather/commit/4dc8785a4ab57e13a1179beece163bee25b6bb89
