### ISSUE TITLE
Unknown Icon

### ISSUE THREAD

**Issue by lseufer** [bieniu/ha-accuweather#6]
When there is no corresponding icon in HA, a big exclamation mark is displayed.

Here it is:
<img width="415" alt="Screenshot 2020-08-06 at 20 52 59" src="https://user-images.githubusercontent.com/7261297/89571022-47507200-d827-11ea-84c3-70ab2ed60841.png">

And in the detailed view:
<img width="378" alt="Screenshot 2020-08-06 at 20 53 09" src="https://user-images.githubusercontent.com/7261297/89571029-4ae3f900-d827-11ea-97da-a8bad9c45db7.png">

And the one which should be displayed
<img width="384" alt="Screenshot 2020-08-06 at 20 54 30" src="https://user-images.githubusercontent.com/7261297/89571033-4cadbc80-d827-11ea-8844-44cbb6eded30.png">

**Comment by bieniu** [comment]
This icon means exceptional weather condition, not an unknown icon.

**Comment by lseufer** [comment]
Any idea how to make it smaller?

**Comment by bieniu** [comment]
I don't know. It's a  frontend issue.
